# Labelの追加・マッチパターンは下記参照
# https://github.com/actions/labeler#create-githublabeleryml
CI/CD:
  - any: ['.github/**/*']

frontend:
  - any: ['frontend/**/*']

backend:
  - any: ['backend/**/*']

infra:
  - any: ['infra/**/*']
