name: Run commitlint on PR

on: [pull_request]

jobs:
  run-commitlint-on-pr:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # https://github.com/actions/checkout/releases/tag/v3.5.3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # https://github.com/actions/setup-node/releases/tag/v3.7.0
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
