name: Lint GitHub Actions workflows
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '.github/workflows/*'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
